Update remi & use php 8 on CentOS
pterodactyl/documentation pull request #433
Opened 2022-01-30 03:06 UTC by markd69

Update Remi to 9 and use PHP 8.0

Also noted that CentOS 8 is EOL.

2022-01-31 18:22 UTC, Software-Noob requested changes

2022-01-31 18:22 UTC, Software-Noob commented on community/installation-guides/panel/centos8.md
> +dnf install https://rpms.remirepo.net/enterprise/remi-release-9.rpm
This should be 8 and not 9

2022-02-01 17:05 UTC, Software-Noob commented
Can you please update all the other sections that specify PHP 7.4 to use 8.0 instead for consistency? There's the title in centos8.md and comment in centos7.md that still mentions PHP 7.4

2022-02-01 23:59 UTC, markd69 commented
> Can you please update all the other sections that specify PHP 7.4 to use 8.0 instead for consistency? There's the title in centos8.md and comment in centos7.md that still mentions PHP 7.4

Sorry about that, done.

2022-02-12 11:32 UTC, Software-Noob approved these changes
LGTM, thank you for contributing :+1:

2022-02-12 11:34 UTC, merged