Future-proof php version in schedules troubleshooting guide
pterodactyl/documentation pull request #623
Opened 2024-11-23 23:43 UTC by Loki-101

Previous "up to" isn't specific enough now that there's only two supported versions, and I may as well use the page that's built for this exact purpose if I'm updating it.

2024-11-24 01:42 UTC, rowansc1 requested changes
Line 143 is incorrect, the `<>` are not needed in the context you are using and should be removed. 

The `<>` are used independently when you want to pop something out which is just a link, not an embedded link, such as in the contab guru link below. 

Example: 
```
[this page](https://pterodactyl.io/panel/1.0/updating.html#panel-version-requirements)
```

Thanks for your PR!

2024-11-24 01:43 UTC, rowansc1 requested changes
Line 143 is incorrect, the `<>` are not needed in the context you are using and should be removed. 

The `<>` are used independently when you want to pop something out which is just a link, not an embedded link, such as in the contab guru link below. 

Example: 
```
[this page](https://pterodactyl.io/panel/1.0/updating.html#panel-version-requirements)
```

Thanks for your PR!

2024-11-24 01:43 UTC, rowansc1 commented on panel/1.0/troubleshooting.md
> +- Check your php version ``php -v`` - [this page](<https://pterodactyl.io/panel/1.0/updating.html#panel-version-requirements>) will tell you what versions of php are supported by what versions of the
Line 143 is incorrect, the `<>` are not needed in the context you are using and should be removed. 

The `<>` are used independently when you want to pop something out which is just a link, not an embedded link, such as in the contab guru link below. 

Example: 
```
[this page](https://pterodactyl.io/panel/1.0/updating.html#panel-version-requirements)
```

Thanks for your PR!

2024-11-24 02:02 UTC, Loki-101 commented
Whoops, too used to markdown for Discord. I removed the <> for crontab.guru while I was at it; that was leftover from when I was sending this guide in Discord before the original PR was accepted.

2024-12-11 02:07 UTC, closed without merging

2024-12-11 02:23 UTC, Loki-101 commented
Whoops, I was cleaning up old repositories and forgot I had this PR open. I'll make a new one.